First attemtp
alexwti/java-shareit pull request #1
Opened 2023-01-19 15:53 UTC by alexwti

2023-01-20 16:39 UTC, ErkinKasymaliev requested changes
Привет, неплохая работа!
оставил комменты

2023-01-20 16:39 UTC, ErkinKasymaliev commented on src/main/java/ru/practicum/shareit/user/storage/UserStorageImpl.java
> +        emailValidate(userDto.getEmail());
всю валидацию надо убрать в слой сервиса, в storage-ы должны приходить уже валидированный данные

2023-01-20 16:39 UTC, ErkinKasymaliev commented on src/main/java/ru/practicum/shareit/user/storage/UserStorageImpl.java
> +    private void emailValidate(String email) {
надо убрать в сервисы

2023-01-20 16:39 UTC, ErkinKasymaliev commented on src/main/java/ru/practicum/shareit/item/mapper/ItemMapper.java
> +@Getter
тут сеттеры и геттеры не нужны

2023-01-20 16:39 UTC, ErkinKasymaliev commented on src/main/java/ru/practicum/shareit/item/mapper/ItemMapper.java
> +public class ItemMapper {
давайте сделаем так:
создадим интерфейс BaseMapper
interface BaseMapper<D,M> {
      D toDto(M m);
      
     M toModel(D d);

}

а потом будем имплементить все мапперы от него и инжектить их

2023-01-23 09:00 UTC, alexwti commented on src/main/java/ru/practicum/shareit/user/storage/UserStorageImpl.java
> +        emailValidate(userDto.getEmail());
Убрал

2023-01-23 09:00 UTC, alexwti commented on src/main/java/ru/practicum/shareit/user/storage/UserStorageImpl.java
> +    private void emailValidate(String email) {
Убрал

2023-01-23 09:00 UTC, alexwti commented on src/main/java/ru/practicum/shareit/item/mapper/ItemMapper.java
> +@Getter
Убрал

2023-01-23 09:00 UTC, alexwti commented on src/main/java/ru/practicum/shareit/item/mapper/ItemMapper.java
> +public class ItemMapper {
Сделал. Интересно получилось

2023-01-23 10:31 UTC, alexwti commented
> Привет, неплохая работа! оставил комменты

2023-01-23 17:50 UTC, ErkinKasymaliev requested changes
привет, оставил 1 коммент

2023-01-23 17:50 UTC, ErkinKasymaliev commented on src/main/java/ru/practicum/shareit/item/storage/ItemStorageImpl.java
> +    private final ItemMapperImpl itemMapper = new ItemMapperImpl();
над каждым маппером можете поставить аннотацию @Component, например над ItemMapperImpl, да и назвать его можете просто ItemMapper, имплементятся же от BaseMapper. А здесь уже по-спринговски инжектить. Но! Маппинг лучше опять в слой сервиса уберите. в дао слое всегда желательно получать сущности и отдавать их же.

2023-01-24 06:50 UTC, ErkinKasymaliev approved these changes
привет, работа принята!
На будущее - коммиты пишите более подробно например и желательно на английском, например, "removed Dto return types from storages, added @Component to ItemMapper, UserMapper"

2023-01-24 09:35 UTC, merged