Add bookings
alexwti/java-shareit pull request #2
Opened 2023-02-06 12:27 UTC by alexwti

2023-02-07 11:48 UTC, ErkinKasymaliev requested changes
привет, очень хорошая работа!
Оставил пару комментов.

2023-02-07 11:48 UTC, ErkinKasymaliev commented on src/main/java/ru/practicum/shareit/booking/dto/BookingDtoShortC.java
> +public class BookingDtoShortC {
файл кажется лишний, удалите

2023-02-07 11:48 UTC, ErkinKasymaliev commented on src/main/java/ru/practicum/shareit/booking/dto/BookingDto.java
> +    private Item item;
@JsonIdentityInfo(generator = ObjectIdGenerators.PropertyGenerator.class, property = "id")
@JsonIdentityReference(alwaysAsId = true)
@JsonProperty("itemId")
добавьте эти аннотации и не надо создавать short классы

2023-02-07 20:16 UTC, alexwti commented on src/main/java/ru/practicum/shareit/booking/dto/BookingDtoShortC.java
> +public class BookingDtoShortC {
Удалил

2023-02-07 20:17 UTC, alexwti commented on src/main/java/ru/practicum/shareit/booking/dto/BookingDto.java
> +    private Item item;
Почему-то так у меня не заработало, получился забавный вариант, но как ни странно - работает

2023-02-08 06:13 UTC, ErkinKasymaliev approved these changes
привет, интересное решение придумали)
работа принята

2023-02-15 17:54 UTC, merged