Feat: Added Requests, tests
alexwti/java-shareit pull request #3
Opened 2023-02-22 17:15 UTC by alexwti

2023-02-25 07:07 UTC, ErkinKasymaliev requested changes
привет, оставил комменты

2023-02-25 07:07 UTC, ErkinKasymaliev commented on src/main/java/ru/practicum/shareit/item/controller/ItemController.java
> +    public List<ItemDtoExt> getAllItemsOfOwner(@RequestHeader(sharerUserId) long id) {
по ТЗ:
...Поэтому, чтобы приложение было комфортным для пользователей, а также быстро работало, вам предстоит добавить пагинацию в эндпоинты GET /items, GET /items/search, ...  
также почему у вас нет GET /items/search?

2023-02-25 07:07 UTC, ErkinKasymaliev commented on src/test/java/ru/practicum/shareit/booking/controller/BookingControllerTest.java
> +                .andExpect(content().json(mapper.writeValueAsString(bookingDto)));
тут еще давайте везде заюзаем verify - проверить вызывается нужный метод, в данном случае bookingService.createBooking(),
выглядит примерно так:
verify(bookingService, times(число раз сколько должен был вызваться)).createBooking(anyLong(), any(BookingDto.class))

2023-02-25 07:07 UTC, ErkinKasymaliev commented on src/test/java/ru/practicum/shareit/booking/controller/BookingControllerTest.java
> +                .andExpect(content().json(mapper.writeValueAsString(bookingDto)));
и так желательно во всех тестах контроллеров

2023-02-26 12:46 UTC, alexwti commented on src/test/java/ru/practicum/shareit/booking/controller/BookingControllerTest.java
> +                .andExpect(content().json(mapper.writeValueAsString(bookingDto)));
Сделал

2023-02-26 12:47 UTC, alexwti commented on src/main/java/ru/practicum/shareit/item/controller/ItemController.java
> +    public List<ItemDtoExt> getAllItemsOfOwner(@RequestHeader(sharerUserId) long id) {
Упс... Добавил

2023-02-26 15:54 UTC, ErkinKasymaliev approved these changes
привет, работа принята

2023-02-27 13:11 UTC, merged