Feat: Added Server, Gateway, tests, Docker
alexwti/java-shareit pull request #4
Opened 2023-03-03 10:41 UTC by alexwti

2023-03-04 07:35 UTC, ErkinKasymaliev requested changes
привет, оставил 1 коммент

2023-03-04 07:35 UTC, ErkinKasymaliev commented on gateway/src/main/java/ru/practicum/shareit/item/controller/ItemController.java
> +    public ResponseEntity<Object> updateItem(@RequestHeader(sharerUserId) long userId, @PathVariable long itemId, @RequestBody ItemDto itemDto) {
почему у вас в патч запросах нет @Valid?

2023-03-05 12:34 UTC, alexwti commented on gateway/src/main/java/ru/practicum/shareit/item/controller/ItemController.java
> +    public ResponseEntity<Object> updateItem(@RequestHeader(sharerUserId) long userId, @PathVariable long itemId, @RequestBody ItemDto itemDto) {
Честно говоря, впал в замешательство. Больше ничего в голову не пришло

2023-03-05 13:37 UTC, ErkinKasymaliev approved these changes
привет, работа принята

2023-03-07 08:21 UTC, merged